import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Fallback from "@/components/Fallback";
import { Toaster } from "sonner";
import Providers from "./provider";
import { getServerSession } from "next-auth";
import { BookingProvider } from "@/context/BookingContext";
import { authOptions } from "./api/auth/[...nextauth]/route";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WhooshBus - Travel Safe",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions); // ✅ SSR session fetch once

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <BookingProvider>
          <Suspense fallback={<Fallback />}>
            <Providers session={session}>
              {children}
              <Toaster richColors position="top-right" />
            </Providers>
          </Suspense>
        </BookingProvider>
      </body>
    </html>
  );
}
